#!/usr/bin/env bash

wget --no-check-certificate  https://raw.githubusercontent.com/teddysun/shadowsocks_install/master/shadowsocks.sh
chmod +x shadowsocks.sh
./shadowsocks.sh 2>&1 | tee shadowsocks.log

wget -O /etc/shadowsocks.json https://raw.githubusercontent.com/melos-c/VtR/master/ssconfig.json
wget -O ssEditor.sh https://raw.githubusercontent.com/melos-c/VtR/master/ssConfigEditor.sh
chmod +x ssEditor.sh

