#!/usr/bin/env bash
#https://raw.githubusercontent.com/melos-c/VtR/master/vray

date -R
echo "====== Installing Prerequisite ==========="
read -p "Press [Enter] key to Continue..."
yum install -y zip unzip
yum install net-tools
yum -y update


echo "====== Openning Necessary Ports =========="
read -p "Press [Enter] key to Continue..."
firewall-cmd --zone=public --add-port=10086/tcp --permanent
firewall-cmd --zone=public --add-port=10087/tcp --permanent
firewall-cmd --zone=public --add-port=80/tcp --permanent #used for acme.sh issue and update certs.
firewall-cmd --zone=public --add-port=443/tcp --permanent
firewall-cmd --zone=public --add-port=444/tcp --permanent
#firewall-cmd --permanent --zone=public --add-service=http 
#firewall-cmd --permanent --zone=public --add-service=https
firewall-cmd --reload

#====ACME+SSL==================================
echo "====== Installing ACME and SSL Cert & Key ====="
read -p "Press [Enter] key to Continue..."
yum -y install socat.x86_64
curl  https://get.acme.sh | sh
source ~/.bashrc
~/.acme.sh/acme.sh --upgrade --auto-upgrade
#read -p "Input Domain Name:" domain
sudo ~/.acme.sh/acme.sh --issue -d huaxiatech.buzz --standalone -k ec-256
#将证书生成到 /etc/v2ray/ 文件夹，更新证书之后还得把新证书生成到 /etc/v2ray
sudo ~/.acme.sh/acme.sh --installcert -d huaxiatech.buzz --fullchainpath /usr/local/etc/v2ray/v2ray.crt --keypath /usr/local/etc/v2ray/v2ray.key --ecc
chmod 666 /usr/local/etc/v2ray/v2ray.key
# Manually renew the cert when it expires...
#sudo ~/.acme.sh/acme.sh --renew -d huaxiatech.xyz --force --ecc
#acme.sh --cron -f

echo "===== Installing V2Ray ==================="
read -p "Press [Enter] key to Continue..."
bash <(curl -L https://raw.githubusercontent.com/v2fly/fhs-install-v2ray/master/install-release.sh)
read -p "Full File Name of Config to be Downloaded:" downloadconfig
wget -O /usr/local/etc/v2ray/config.json https://raw.githubusercontent.com/melos-c/VtR/master/${downloadconfig}
clear

systemctl enable v2ray
systemctl start v2ray
systemctl status v2ray

clear
echo "====== List the Listening Ports =========="
netstat -lpnt

echo "====== Installing BBR ===================="
read -p "Press [Enter] key to Continue..."
wget –no-check-certificate https://github.com/teddysun/across/raw/master/bbr.sh
chmod +x bbr.sh
./bbr.sh
reboot

# Verify if BBR is installed successfully.
#lsmod | grep bbr
#cd ..
#cd ~
